Gibberlings3/iesdp

_sass/_general.scss
Hey that did it :) only changes to css file
=> Changed table design and fixed wrapping

scripting/actions/bgeeactions.htm
Added missing bgee action descriptions for action 359, 361, 364, 365, 366, 367, 368, 369 and 370 by argent from the forum.
=> Added some missing bgee action descriptions by argent

scripting/actions/bgeeactions.htm
Updated all occurances of bg2 ids references to the bgee ones. Fixes #38
=> Fixed #38 - BG2 ids files referenced from BG(2)EE actions.

file_formats/ie_formats/are_v1.htm
Fix typo as per http://gibberlings3.net/forums/index.php?showtopic=27724
=> Fix typo as per http://gibberlings3.net/forums/index.php?showtopic=27724

file_formats/ie_formats/are_v1.htm, file_formats/ie_formats/are_v9.1.htm
As per http://gibberlings3.net/forums/index.php?showtopic=27949
=> Trap detection difficulty 100+ prevents trap being detected

scripting/actions/bg1actions.htm, scripting/actions/bg2actions.htm, scripting/actions/bgeeactions.htm, scripting/actions/iwd2actions.htm, scripting/actions/pstactions.htm, scripting/actions/totlactions.htm
As per http://gibberlings3.net/forums/index.php?showtopic=27922
=> Amend example so as not to imply specific value can exceed 255

file_formats/general.htm
Add
0x3ff	.wbm
0x405	.glsl (EE)
0x408	.menu (EE)
0x409	.lua (EE)
0x40a	.ttf (EE)
0x40b	.png (EE patch 2.0)
Amend
0x44c	.bah
Remove
0x401
As per
http://gibberlings3.net/forums/index.php?showtopic=28962
http://gibberlings3.net/forums/index.php?showtopic=26057
http://gibberlings3.net/forums/index.php?showtopic=27942
=> Update resource types

file_formats/ie_formats/gam_v1.1.htm
As per http://gibberlings3.net/forums/index.php?showtopic=26026
There's no way to test this AFAIK but the struct size is the same, there's no other known use, and it's information from the Beamdog info dump.
=> Update GAM 1.1 variable section

scripting/actions/bg2actions.htm, scripting/actions/bgeeactions.htm
As per http://gibberlings3.net/forums/index.php?showtopic=27794.
=> Add alias for CreateCratureObject and CreateCreatureObjectCopy

file_formats/index.htm
Just added for the sake of completeness.
=> Update list of available IE file formats

file_formats/ie_formats/itm_v1.htm
=> Removed outdated info from ITM V1 format description

scripting/actions/bgeeactions.htm, scripting/triggers/bg2triggers.htm, scripting/triggers/bgeetriggers.htm
Based on topics [#1](http://gibberlings3.net/forums/index.php?showtopic=29012) and [#2](http://gibberlings3.net/forums/index.php?showtopic=29013) on G3 Forums.
=> Update trigger and action descriptions

file_formats/ie_formats/itm_v1.1.htm, file_formats/ie_formats/itm_v1.htm, file_formats/ie_formats/itm_v2.0.htm
* Correct offsets/sizes
* Correct HTML tag errors
* Unify jargon between version
=> update ITM file format descriptions

file_formats/ie_formats/spl_v1.htm
Ref https://www.gibberlings3.net/forums/topic/7446-hardcoded-projectiles/?tab=comments#comment-66084
=> note that spl pro value is off-by-one from projectl.ids values

.gitignore, file_formats/ie_formats/spl_v1.htm
Added info about Limit Effect Stacking flags and ids from TobEx
=> Tobex effects stacking info

file_formats/ie_formats/eff_v2.htm, file_formats/ie_formats/itm_v1.htm, file_formats/ie_formats/spl_v1.htm
completing https://github.com/Gibberlings3/iesdp/pull/92
=> added tobex effect stacking info to itm v1 and eff v2 formats

_data/actions/269.yml
=> added minor extra info about DisplayStringHead

_opcodes/op248.html
According to my results, it works the same way in classic ToB.
=> opcode 248: works the same in classic

_opcodes/op126.html, _opcodes/op176.html
Just a quick note about this EE behavior.
=> Opcodes 126 and 176: p2 = 5

_opcodes/op220.html, _opcodes/op221.html, _opcodes/op346-bgee.html, files/2da/2da_bgee/mschool.htm, files/2da/2da_bgee/msectype.htm
This small PR addresses an issue regarding op220/221 descriptions and clarifies a couple of things about `MSCHOOL.2DA` and `MSECTYPE.2DA`.
=> "MSCHOOL.2DA", "MSECTYPE.2DA", op220/221

file_formats/ie_formats/ini.htm
Included detailed information about the area-related creature spawning format.
=> Improved INI file format description

_opcodes/op066.html, file_formats/ie_formats/cre_v1.htm
=> Opcode #66

file_formats/ie_formats/cre_v1.htm, files/ids/bgee/stats.htm
Added some more info about Morale (`CRE V1.0 @ 0x23F`), Morale Break (`CRE V1.0 @ 0x240`), Morale Recovery (`CRE V1.0 @ 0x242`).
=> Morale, Morale Break, Morale Recovery

_data/README.md, _data/file_formats/eff_v2/body.yml
Here's data [readme](https://github.com/BGforgeNet/iesdp/tree/fix-data-formatting/_data).
Eff v2 timing table:
Ref #127.
=> Fix data formatting

_data/file_formats/eff_v1/header.yml, _data/file_formats/eff_v2/body.yml, _opcodes/op182-bgee.html, _opcodes/op182.html, _opcodes/op321-bgee.html
- Added some rudimentary info about how `op182` is supposed to work and why it is currently bugged.
- Added some extra info about `op321`.
=> Opcode #182 / opcode #321

_opcodes/op236.html, file_formats/ie_formats/cre_v1.htm, files/ids/bgee/gender.htm
Added some more details about how `op236, param2=3` (Simulacrum) is supposed to work and why it is not working as expected.
=> Opcode #236 bug

_data/file_formats/itm_v1/extended_header.yml, _opcodes/op190.html, files/2da/2da_bgee/wspecial.htm, files/2da/2da_tob/wspecial.htm
Added a side note about how this file is partially bugged on EE games.
=> "wspecial.2da"

appendices/clua/bgee.htm
Update of CLUA console command `Eval`.
First discovered by Bubb: https://forums.beamdog.com/discussion/comment/1029525/#Comment_1029525
=> CLUA command update

_opcodes/op235-bgee.html, files/ids/bgee/animate.htm
- The page now clearly states the animations that are hardcoded to be immune to this effect.
- Added some info about how this opcode interacts with Magic Resistance.
=> Opcode #235

deploy.sh
=> "Automaton" is at least 4.6 times cooler than "automation"

appendices/avatarnaming.htm
Clearly an urgent, critical update
=> typo, represending > representing

file_formats/ie_formats/are_v1.htm
Added separate list of PSTEE-specific animation flags.
=> Update ARE V1 animation flags

_data/file_formats/eff_v1/header.yml
Source: https://www.gibberlings3.net/forums/topic/34892-code-code-fixes-aka-stuff-we-cant-fix/?do=findComment&comment=335038
=> Information about effect probabilities rolls

_opcodes/op033.html
Sorry, but I seem to have forgotten a few things about the previous PR :/
=> op33: fix include relurl + typo stats#59 ⇒ stats#9

scripting/triggers/bgeetriggers.htm
Based on this: https://www.gibberlings3.net/forums/topic/38976-does-exists-trigger-works-as-described/
=> Improve "Exists" description

scripting/triggers/bgeetriggers.htm
Based on the information from here: https://www.gibberlings3.net/forums/topic/38976-does-exists-trigger-works-as-described/
=> Update InMyArea trigger description.

file_formats/ie_formats/are_v1.htm, files/2da/2da_tob/index.htm, files/2da/2da_tob/spawngrp.htm
- Added SPAWNGRP.2DA description to BG2:ToB section
- Updated SPAWNGRP.2DA description
- Updated descriptions in ARE V1.0 spawn point and rest interruption sections
=> Update spawngrp.2da description

_data/actions/67.yml, _opcodes/op048.html, _opcodes/op067.html, _opcodes/op271-bgee.html, _opcodes/op320-bgee.html, _opcodes/op323-bgee.html, files/ids/bgee/stats.htm
Most of them can be read here : https://www.gibberlings3.net/forums/topic/39006-some-additions-opcodes-74-271-and-323/
=> Opcode - Some fixes

file_formats/ie_formats/cre_v9.htm
Minor update, courtesy of Bubb.
=> IWD cre file info from Bubb on Discord

_data/actions/375-bgee.yml, _data/actions/382-bgee.yml, _data/actions/406-bgee.yml, _data/actions/408-bgee.yml, _data/actions/417-pstee.yml, _data/actions/447-pstee.yml
Added descriptions for:
- 375 SetNoWaitX(I:SetReset*Boolean)
- 382 JoinPartyOverride()
- 406 ContinueGame(I:State*Boolean)
- 408 DisplayStringPointLog(P:Location*,I:Strref*)
- 417 SetNamelessDisguise(I:DisguiseNum*Disguise)
- 447 TimedMoveToPoint(P:Point*,I:Time*)
=> Document more EE-specific script actions

_data/file_formats/eff_v1/header.yml, _data/file_formats/eff_v2/body.yml
=> Clarify "holes" in the saving throw bits
